apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol
  labels:
    app: webapp
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 64Mi
  hostPath:
    path: /tmp/PVData
  persistentVolumeReclaimPolicy: Retain