apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-vol-claim
spec:   
  selector:
    matchLabels:
      app: webapp
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi